services:
  gateway:
    build:
      context: ./api_gateway_service
      dockerfile: dockerfile
    environment:
      - GATEWAY_PORT
      - TEMPLATE_PORT
      - ANALYTICS_SERVICE_PORT
      - CHATBOT_SERVICE_PORT
      - FILE_SERVICE_PORT
      - DB_URL=jdbc:sqlite:db.db
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"

  analytics_service:
    build:
      context: ./analytics_service
      dockerfile: dockerfile
    environment:
      - GATEWAY_PORT
      - TEMPLATE_PORT
      - ANALYTICS_SERVICE_PORT
      - CHATBOT_SERVICE_PORT
      - FILE_SERVICE_PORT
    ports:
      - "${ANALYTICS_SERVICE_PORT}:${ANALYTICS_SERVICE_PORT}"

  chatbot_service:
    build:
      context: ./chatbot_service
      dockerfile: dockerfile
    environment:
      - GATEWAY_PORT
      - TEMPLATE_PORT
      - ANALYTICS_SERVICE_PORT
      - CHATBOT_SERVICE_PORT
      - FILE_SERVICE_PORT
    ports:
      - "${CHATBOT_SERVICE_PORT}:${CHATBOT_SERVICE_PORT}"

  # template:
  #   build:
  #     context: ./template_service
  #     dockerfile: dockerfile
  #   environment:
  #     - GATEWAY_PORT
  #     - TEMPLATE_PORT
  #   ports:
  #     - "${TEMPLATE_PORT}:${TEMPLATE_PORT}"

  file:
    build:
      context: ./file_service
      dockerfile: dockerfile
    environment:
      - GATEWAY_PORT
      - TEMPLATE_PORT
      - ANALYTICS_SERVICE_PORT
      - CHATBOT_SERVICE_PORT
      - FILE_SERVICE_PORT
      - DB_URL=jdbc:sqlite:db.db
      - CHUNK_SIZE=1024
      - JWT_EXPIRY_IN_SECONDS=3600
    ports:
      - "${FILE_SERVICE_PORT}:${FILE_SERVICE_PORT}"
