name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            target
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
            
      - name: Check Scala version
        run: sbt --client 'scalaVersion'
        
      - name: Run tests
        run: sbt test
        
      - name: Run http4s tests (if separate)
        run: sbt 'project http4sModule' test
        # Replace 'http4sModule' with your actual module name if http4s is in a submodule
        
      - name: Check coverage (optional)
        run: sbt coverage test coverageReport
        # Requires sbt-scoverage plugin
        
      - name: Upload coverage (optional)
        if: success()
        uses: codecov/codecov-action@v3
        with:
          files: ./target/scala-3.3.5/scoverage-report/scoverage.xml
          # Adjust path based on your project structure
