name: Scala Microservices CI

on:
  push:
    branches: [ main, CI ]
  pull_request:
    branches: [ main, CI ]

jobs:
  api_gateway_test:
    name: API Gateway Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier
            target
          key: ${{ runner.os }}-api-gateway-${{ hashFiles('api_gateway_service/build.sbt') }}
          
      - name: Run tests
        working-directory: ./api_gateway_service
        run: sbt test

  chatbot_test:
    name: Chatbot Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier
            target
          key: ${{ runner.os }}-chatbot-${{ hashFiles('chatbot_service/build.sbt') }}
          
      - name: Run tests
        working-directory: ./chatbot_service
        run: sbt test

  file_service_test:
    name: File Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier
            target
          key: ${{ runner.os }}-file-service-${{ hashFiles('file_service/build.sbt') }}
          
      - name: Run tests
        working-directory: ./file_service
        run: sbt test

  metadata_service_test:
    name: Metadata Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier
            target
          key: ${{ runner.os }}-metadata-service-${{ hashFiles('metadata_service/build.sbt') }}
          
      - name: Run tests
        working-directory: ./metadata_service
        run: sbt test
