name: Scala CI

on:
  push:
    branches: [ CI ]  # Changed to target your CI branch
  pull_request:
    branches: [ main, CI ]  # Include both main and CI branches

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
          
      - name: Install sbt
        run: |
          sudo apt-get update
          sudo apt-get install -y sbt
          
      - name: Verify installations
        run: |
          java -version
          sbt --version
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier
            target
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/build.properties') }}
          
      - name: Run tests
        run: sbt +test  # The '+' tests across all Scala versions if cross-built
        
      - name: Run http4s tests
        if: success()  # Only run if previous steps succeeded
        run: sbt 'project http4sModule' test  # Update with your actual module name
