name: Scala CI

on:
  push:
    branches: [ CI ]
  pull_request:
    branches: [ main, CI ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
          
      - name: Install sbt directly
        run: |
          # Download and extract sbt directly
          SBT_VERSION=1.9.7
          mkdir -p ~/bin/sbt
          curl -fL https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz | tar xz -C ~/bin/sbt --strip-components=1
          echo "$HOME/bin/sbt/bin" >> $GITHUB_PATH
          
      - name: Verify installations
        run: |
          java -version
          sbt --version
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier
            target
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/build.properties') }}
          
      - name: Run tests
        run: sbt +test
        
      - name: Run http4s tests
        if: success()
        run: sbt 'project http4sModule' test
