name: Scala Microservices CI

on:
  push:
    branches: [ main, CI ]
  pull_request:
    branches: [ main, CI ]

jobs:
  api_gateway_test:
    name: API Gateway Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Install sbt (System-wide)
        run: |
          # Install sbt via official package
          sudo apt-get update
          sudo apt-get install -y apt-transport-https curl gnupg
          echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
          echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --import
          sudo chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg
          sudo apt-get update
          sudo apt-get install -y sbt
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier
            target
          key: ${{ runner.os }}-api-gateway-${{ hashFiles('api_gateway_service/build.sbt') }}
          
      - name: Run tests
        working-directory: ./api_gateway_service
        run: sbt test

  chatbot_test:
    name: Chatbot Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier
            target
          key: ${{ runner.os }}-chatbot-${{ hashFiles('chatbot_service/build.sbt') }}
          
      - name: Run tests
        working-directory: ./chatbot_service
        run: sbt test

  file_service_test:
    name: File Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier
            target
          key: ${{ runner.os }}-file-service-${{ hashFiles('file_service/build.sbt') }}
          
      - name: Run tests
        working-directory: ./file_service
        run: sbt test

  metadata_service_test:
    name: Metadata Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier
            target
          key: ${{ runner.os }}-metadata-service-${{ hashFiles('metadata_service/build.sbt') }}
          
      - name: Run tests
        working-directory: ./metadata_service
        run: sbt test
